### ISSUE TITLE
Error parsing config file

### ISSUE THREAD

**Issue by edin702** [hairyhenderson/hitron_coda_exporter#110]
caller=main.go:165 level=error msg="Error parsing config file" err="yaml: input error: read hitron_coda.yml: is a directory"

Unable to get this running. Any help would be amazing thanks!

**Comment by hairyhenderson** [comment]
@edin702 what exact command and arguments did you run, and on which operating system? Is it running in a container?

**Comment by edin702** [comment]
I was able to figure it out was an issue on my end! But did end up with a different error which I posted a new issue. Thanks for responding!
