### ISSUE TITLE
Docker exists

### ISSUE THREAD

**Issue by kronkinatorix** [hairyhenderson/hitron_coda_exporter#153]
Barring the spontaneous combustion of everyone involved in its creation and maintenance, which I don't think will happen, it would be great to get some more detailed install instructions for not docker, since using docker is right below ripping my own eyes out on the "things I'd like to do" list.

**Comment by hairyhenderson** [comment]
😅 I think this wins some kind of award for most-awkwardly-worded-passive-aggressive issue ever, maybe...

I think what your saying is that you take issue with the existence of Docker (?), which is _way_ beyond the scope of this particular repo!

If you read the current README, you'll see this:

> You can build a binary for your system with `go get github.com/hairyhenderson/hitron_coda_exporter`, or you can use a [pre-built Docker image](https://hub.docker.com/r/hairyhenderson/hitron_coda_exporter):

So, there's an alternative to the Docker image: run `go get github.com/hairyhenderson/hitron_coda_exporter`

A simpler approach could be to publish binaries to GitHub and institute a release process. To be perfectly honest though, I don't use this anymore and this adds a level of maintenance effort I'm not really interested in.

PRs are accepted though if you have any suggestions...
